# Generated by Django 4.0.4 on 2022-04-25 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('sinopsis', models.CharField(max_length=50)),
                ('año', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=50)),
                ('actores', models.CharField(max_length=50)),
                ('puntuacion', models.CharField(max_length=50)),
                ('visualizacion', models.CharField(max_length=50)),
            ],
        ),
    ]
