# Generated by Django 4.0.4 on 2022-04-26 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcinebot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='imagen',
            field=models.ImageField(null=True, upload_to='peliculas'),
        ),
    ]
