# Generated by Django 4.0.4 on 2022-04-30 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcinebot', '0003_alter_pelicula_sinopsis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=200, verbose_name='Apellido')),
            ],
        ),
    ]
