# Generated by Django 4.0.4 on 2022-05-06 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcinebot', '0004_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
